#development: &default
#  adapter: postgresql
#  encoding: unicode
#  database: svd_dev
#  pool: 20
#  host: localhost
#  port: 5432
#  username: dobrik
#
#test:
#  <<: *default
#  database: svd_test
#
#production:
#  <<: *default
#  database: svd_prod
#
development:
  url: postgresql://svdlab:123456789@postgres:5432/svd_dev?encoding=utf8&pool=5&timeout=5000

test:
  url: postgresql://svdlab:123456789@postgres:5432/svd_test?encoding=utf8&pool=5&timeout=5000

production:
  url: postgresql://svdlab:123456789@postgres:5432/svd_prod?encoding=utf8&pool=5&timeout=5000

